# Generated by Django 5.2.1 on 2025-05-25 13:05

import django.db.models.deletion
from django.db import migrations, models

import example_project


def set_default_accounting_year(apps, schema_editor):
    AccountingYear = apps.get_model("example_project", "AccountingYear")
    if AccountingYear.objects.count() == 0:
        AccountingYear.objects.create(
            name="Default Year",
            is_default=True,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("example_project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountingYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "unique_together": {("name", "is_default")},
            },
        ),
        migrations.AddField(
            model_name="inventory",
            name="accounting_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventories",
                to="example_project.accountingyear",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="accounting_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="example_project.accountingyear",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="accounting_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="example_project.accountingyear",
            ),
        ),
        migrations.RunPython(set_default_accounting_year, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="inventory",
            name="accounting_year",
            field=models.ForeignKey(
                default=example_project.models.get_default_accounting_year_id,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="inventories",
                to="example_project.accountingyear",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="accounting_year",
            field=models.ForeignKey(
                default=example_project.models.get_default_accounting_year_id,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="items",
                to="example_project.accountingyear",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="accounting_year",
            field=models.ForeignKey(
                default=example_project.models.get_default_accounting_year_id,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="products",
                to="example_project.accountingyear",
            ),
        ),
    ]
